version: '2'
services:
  eureka:
    build: ../eureka
    image: eureka
    ports:
      - "8761"

  web:
    build: ../web
    image: web
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka
    ports:
      - "8080"
      
  bookservice:
    build: ../bookservice
    image: bookservice
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka:8761/eureka
